# Generated by Django 3.1.6 on 2021-03-07 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, max_length=10000)),
                ('thumbnail', models.CharField(blank=True, max_length=255)),
                ('tags', models.TextField(blank=True, max_length=500)),
                ('typePost', models.CharField(choices=[('Text', 'Text'), ('Activity', 'Activity'), ('Artifact', 'Artifact')], default='Text', max_length=20)),
                ('typeId', models.IntegerField()),
                ('rate', models.CharField(blank=True, max_length=255)),
                ('dateCreated', models.DateField(null=True)),
                ('assets', models.JSONField(blank=True, max_length=2000)),
                ('comments', models.TextField(blank=True, max_length=6000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
