# Generated by Django 3.1.6 on 2022-02-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210430_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='jobs',
            field=models.TextField(blank=True, max_length=6000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='persons',
            field=models.TextField(blank=True, max_length=6000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='skills',
            field=models.TextField(blank=True, max_length=6000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.CharField(blank=True, default='01-image.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='typeId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='typePost',
            field=models.CharField(choices=[('Text', 'Text'), ('Activity', 'Activity'), ('Artifact', 'Artifact')], default='Artifact', max_length=20),
        ),
    ]
