# Generated by Django 3.1.6 on 2022-02-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220201_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(default='01-image.jpg', upload_to=''),
        ),
    ]
