# Generated by Django 3.1.6 on 2022-02-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220201_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.FilePathField(default='01-image.jpg'),
        ),
    ]
