# Generated by Django 3.1.6 on 2022-02-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220201_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.TextField(default='01-image.jpg'),
        ),
    ]
