# Generated by Django 3.1.6 on 2022-02-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220201_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='jobs',
            field=models.JSONField(default='{}'),
        ),
    ]
