# Generated by Django 3.1.6 on 2022-02-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20220201_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='jobs',
            field=models.TextField(blank=True, max_length=6000, null=True),
        ),
    ]
