# Generated by Django 3.1.6 on 2022-02-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20220201_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='jobs',
            field=models.TextField(default='', max_length=6000),
        ),
    ]
