# Generated by Django 3.1.6 on 2022-02-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20220201_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='jobs',
            field=models.TextField(blank=True, default='', max_length=6000, null=True),
        ),
    ]
